WIP feature/letkf
NOAA-EMC/godas pull request #104
Opened 2019-10-29 04:28 UTC by flampouris

- This PR cleans the scripts for the H(x)  for the LETKF

- WIP

2019-10-29 14:26 UTC, guillaumevernieres commented on jobs/JJOB_DA_PREP
> +if [ $DA_METHOD = 'en' ]; then
"en" is too vague, how about letkf?

2019-10-29 14:27 UTC, guillaumevernieres commented on workflow/defaults/places.yaml
> +  DA_METHOD: en #options 3dvar or en
Same comment as above "letkf" instead of "en"

2019-10-29 14:28 UTC, guillaumevernieres commented on workflow/layout/letkf_only.yaml
> +
Do you need to keep these comments?

2019-10-29 14:42 UTC, guillaumevernieres requested changes
bug/typo in da_letkf_run

2019-10-29 14:42 UTC, guillaumevernieres commented on workflow/layout/letkf_only.yaml
> +
Bug slipped through from the last PR: 
Line 64:      J_JOB: JJOB_DA_LEKTF 
should be 
                  J_JOB: JJOB_DA_**LETKF**

2019-10-29 20:56 UTC, flampouris commented
The commented out code for the group is the next step to support the parallel run of the ensemble members.

2019-10-30 01:27 UTC, guillaumevernieres commented
> The commented out code for the group is the next step to support the parallel run of the ensemble members.

OK, sounds good. letkf test is OK, waiting for the 2 vars to finish.

2019-10-30 02:15 UTC, guillaumevernieres approved these changes
:+1:

2019-10-30 02:15 UTC, merged

2019-10-30 02:17 UTC, flampouris commented
one step closer :)