Feature/bgc modules
NOAA-EMC/godas pull request #163
Opened 2020-04-01 14:32 UTC by liuxiao37k

Hello. I added BLING (and a few other biogeochemical) modules to MOM6 as generic tracers such that we can simulate ocean color observables. Temporary solutions to 1) checking out and 2) building ocean_BGC modules was added to checkout.sh but these changes eventually need to be moved to the cloning process of NOAA-EMC/DATM-MOM6-CICE5 (because ocean_BGC modules are essentially part of it) and NOAA-EMC/MOM6-interface/compile.sh. Also, I believe that eventually we would want to control the options in compile.sh (e.g. compile_MOM6_LIB=1/0, compile_MOM6_BGC_LIB=1/0, etc) from yaml file(s). For now, I just added a flag for optional compiling for MOM6_BGC_LIB. Please let's discuss how we want to proceed. Thanks.

2020-04-01 15:12 UTC, flampouris requested changes
@liuxiao37k very good, it's a great start! 

I have not run the system, but let's use this opportunity to see some details about the PRs and git in general. 

0. The requests and comments during the PRs are part of the scientific/technical conversation. 
 
1. I assume that you saw a general PR template, for the PR.
For the documentation of the code update and simplifying the PR process for the reviewers, you should use it. You do not have to add information to all the entries, e.g. not all are applicable or there is some redundancy, etc. 

This step is obligatory for all the PRs.

2.  By using the git, the history of the repository retains the authorship, so the developer takes credit for their work. We do not add our names in the code and we try having minimum documentation in the code, just referencing what a specific portion of the code is related to.

3. Instructions for other users. 
Not much, but at minimum how to install it, how to run it, what are the input files that users can modify, where are the results, anything else that you consider important for somebody to run your test case and have an idea what the output is.

Specific questions
4. See the comments in the code

5. Is installing the bgc optional? 

6. Is running the bgc optional?

2020-04-01 15:12 UTC, flampouris commented on scripts/prep_forecast.sh
> +#field_table (for ocean_BGC) X.Liu 03/27/2020
Remove name/date

2020-04-01 15:12 UTC, flampouris commented on scripts/prep_forecast.sh
> +&generic_tracer_nml
uniform format, for the readability of the code

2020-04-01 15:12 UTC, flampouris commented on scripts/prep_forecast.sh
> +#echo 'RESTART_CHECKSUMS_REQUIRED = False' > $DATA/INPUT/MOM_override
Why is it commented out?

2020-04-01 15:12 UTC, flampouris commented on src/checkout.sh
> +cp -f /scratch2/NCEPDEV/marineda/Xiao.Liu/compile.sh DATM-MOM6-CICE5.fd/MOM6
the actual compile.sh has to be updated, not be overwritten on the fly.

2020-04-01 15:12 UTC, flampouris commented on scripts/templates/MOM_override
> +VERBOSITY = 2
Do we need this activated?

2020-04-10 02:08 UTC, closed without merging

2020-04-10 02:19 UTC, liuxiao37k commented
In stead of requesting to merge, we keep the necessary updates in support of the ocean biogeochemical simulation under the feature/bgc_modules branch. Contributors and users can follow the instructions on the feature branch page (README.md) to clone, build, and run the GODAS workflow with the biogeochemical model (BLING) activated.