Feature/obs scripts
NOAA-EMC/godas pull request #209
Opened 2022-03-29 20:32 UTC by ShastriPaturi

## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
What bug does it fix, or what feature does it add?
Is a change of answers expected from this PR?

### Issue(s) addressed
Addresses #207

2022-03-30 15:17 UTC, jieshunzhu requested changes

2022-03-30 15:17 UTC, jieshunzhu commented on fnmoc/source_fnmoc.sh
> +wget $source/$fn1/$year/${date}00.$fn2.Z --no-check-certificate
updated $yr with $year
wget doest not complete on Orion, but works on Gaea.

2022-04-07 19:11 UTC, jieshunzhu requested changes

2022-04-07 19:11 UTC, jieshunzhu commented on fnmoc/convert_iodav2_fnmoc.sh
> +year=${dtg:0:4}
dtg=>date

2022-04-07 19:11 UTC, jieshunzhu commented on fnmoc/convert_iodav2_fnmoc.sh
> +input_path=$1
$1=>$2

2022-04-07 19:11 UTC, jieshunzhu commented on fnmoc/convert_iodav2_fnmoc.sh
> +echo $dtg DONE
$dtg=>$date

2022-04-07 19:11 UTC, jieshunzhu commented on adt/source.adt.nesdis.sh
> +if validate_url $f; then
The sentence doesnot work.

2022-04-07 19:11 UTC, jieshunzhu commented on nsidc/source_nsidc_daily.sh
> +   wget --ftp-user=anonymous ${source}/ancillary/G02202-cdr-ancillary-nh.nc
nh.nc=>sh.nc

2022-06-24 16:59 UTC, ShastriPaturi commented on fnmoc/convert_iodav2_fnmoc.sh
> +echo $dtg DONE
Corrected

2022-07-05 16:52 UTC, jieshunzhu approved these changes

2022-07-05 17:44 UTC, merged