sanity
NOAA-EMC/godas pull request #224
Opened 2022-04-06 17:55 UTC by mjhossen

## Description

I wrote a python script to find missing files or plotting no of obs or min/max value of a variable, such as absolute dynamic topography. Let's check if there is an issue.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #<issue_number>
- fixes JCSDA/soca-bundle/issues/<issue_number>

## Testing

How were these changes tested?
What compilers / HPCs was it tested with?
Are the changes covered by ctests? (If not, tests should be added first.)

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names for the automated TravisCI tests to pass

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on JCSDA/soca-bundle/pull/<pr_number>
- waiting on JCSDA/oops/pull/<pr_number>

2022-04-06 18:25 UTC, guillaumevernieres commented
Thanks @mjhossen . I'll try to look at it later today, but as a start: Remove the templated text of the pr, or fill it in.

2022-04-06 21:04 UTC, ShastriPaturi commented
@mjhossen please add reviewers in the top right.

2022-04-06 21:06 UTC, ShastriPaturi requested changes
Otherwise looks good.
Thanks

2022-04-06 21:06 UTC, ShastriPaturi commented on mjh_sanity/godas_obssanitycheck.py
> +    #print(args.file_descriptor)
Please remove commented lines

2022-04-06 21:40 UTC, guillaumevernieres requested changes
Thanks for doing that work @mjhossen .
1 - find a better name than `mjh_sanity`. I would suggest something like `obsdiag`, `obscheck` for the name of the folder
2 - Do not EVER commit binary files, unless there is a process in place to handle those, which we don't have in this repo. Remove  the png file please.
3 - Tidy your code a bit, remove the debugging comments for example.

I've added a few comments here and there in the code as well.

2022-04-06 21:40 UTC, guillaumevernieres commented on mjh_sanity/Readme_sc
> +Use the following api to check missing files or plotting number of obs and min/max value:
make use of markdown syntax. The convention is to name this file README.md

2022-04-06 21:40 UTC, guillaumevernieres commented on mjh_sanity/godas_obssanitycheck.py
> +    description = """ Ex: godas_obssanitycheck.py -f adt_c2 -o missing -g ObsValue
the example doesn't fit the arguments below. -s -e are required for example ...

2022-04-06 21:40 UTC, guillaumevernieres commented on mjh_sanity/godas_obssanitycheck.py
> +        help="ioda groups [ObsError, ombg, oman, ObsValue, ...]",
we're only checking the obs, not the DA. Remove `ombg`, `oma`. But more importantly, why should the user need to know what group to use? The group should not be an argument, remove that option.

2022-04-06 21:40 UTC, guillaumevernieres commented on mjh_sanity/godas_obssanitycheck.py
> +    parser.add_argument(
might be ok as a first go, but I'd rather not have to provide a variable. You could get that info from the file without asking the user the variable name.

2022-04-06 21:40 UTC, guillaumevernieres commented on mjh_sanity/godas_obssanitycheck.py
> +    if args.path == None:
just add that as a default value to path L132?

2022-04-06 21:40 UTC, guillaumevernieres commented on mjh_sanity/godas_obssanitycheck.py
> +class Sanity:
You're doing a sanity check, might as well call your class that as well. `SanityCheck` or `ObsSanityCheck` or `ObsCheck` ... Just something more meaningful than `Sanity`.

2022-04-07 14:48 UTC, mjhossen commented
I have edited the script accordingly.

2022-04-07 14:49 UTC, guillaumevernieres commented
@mjhossen , did you mean to close your PR of was it an unfortunate mouse event?

2022-04-07 16:01 UTC, guillaumevernieres approved these changes
:+1: 
Good enough for now. Thanks @mjhossen

2022-04-07 16:12 UTC, ShastriPaturi commented on obssanitycheck/godas_obssanitycheck.py
> +        plt.suptitle("File descriptor: %s"%file_descriptor, y=.95);
I would like the "File Descriptor" removed for the title.
For now it is good.

2022-04-07 16:12 UTC, ShastriPaturi approved these changes
Looks good.
Thanks.

2022-04-07 16:14 UTC, merged

2022-04-09 04:18 UTC, mjhossen commented on obssanitycheck/godas_obssanitycheck.py
> +        plt.suptitle("File descriptor: %s"%file_descriptor, y=.95);
Removed.