Feature/jjob
NOAA-EMC/godas pull request #27
Opened 2019-09-09 20:03 UTC by JianKuang-NOAA

add hera.yaml
moderate clean up

2019-09-09 20:40 UTC, guillaumevernieres requested changes
@JianKuang-NOAA , you forgot to add the hera yaml file.

2019-09-09 20:40 UTC, guillaumevernieres commented on workflow/defaults/places.yaml
> +<<<<<<< HEAD
@JianKuang-NOAA , please remove merge messages.

2019-09-09 21:44 UTC, JianKuang-NOAA commented
I've completed the requested changes. Please check again. Thanks

2019-09-10 00:43 UTC, guillaumevernieres approved these changes
looks good.

2019-09-10 00:44 UTC, merged