obs space monitoring
NOAA-EMC/godas pull request #272
Opened 2022-05-11 15:31 UTC by guillaumevernieres

## Description
This PR adds a tool to plot observation space information available in a ioda file. 
It will produce things like this:

```console
./godas_plotobs.py -f ~/Volumes/orion/runs/s2s/final-0.25/obs_out/2020/2020121218/ctrl/adt_*.nc -g ombg -v absolute_dynamic_topography -b -.2 .2 -c jet -q 0
```

![adt-omb-example](https://user-images.githubusercontent.com/14031856/167887965-aed7fa50-b662-4bb9-a669-48f4eec39253.png)

```console
./godas_plotobs.py -f ~/Volumes/orion/runs/s2s/final-0.25/obs_out/2020/2020121218/ctrl/sst_viirs_npp_l3u_so025.20201212.nc -g ombg -v sea_surface_temperature -b -1 1 -c jet -q 0
```
![sst-omb-example](https://user-images.githubusercontent.com/14031856/167888584-3918e8cf-6b4e-4bca-930f-1c32660e5dd1.png)

2022-05-11 19:03 UTC, ShastriPaturi approved these changes
Looks good. Other options can be added.

2022-05-16 16:44 UTC, mjhossen commented
works perfectly. Did not find any issue.

2022-05-16 17:06 UTC, guillaumevernieres commented
> works perfectly. add some features in the plt.savefig such as bbox_inches='tight', pad_inches = 0.02

Let's not push into each other's branch without doing a PR or making sure with the author of the branch that it is ok @mjhossen. It's not critical in this case, but it certainly is a bad habit.

2022-05-16 17:35 UTC, mjhossen commented
I agree. I put my scripts in the new branch: feature/spaceplot_tool.

2022-05-17 14:24 UTC, ShastriPaturi requested changes

2022-05-17 14:24 UTC, ShastriPaturi commented on monitoring/godas_plotobs.py
> +#!/home/gvernier/anaconda3/bin/python
comment the line

2022-05-17 14:44 UTC, guillaumevernieres commented on monitoring/godas_plotobs.py
> +#!/home/gvernier/anaconda3/bin/python
@ShastriPaturi , done.

2022-05-17 15:03 UTC, ShastriPaturi approved these changes
Thanks

2022-05-17 17:37 UTC, mjhossen commented
good to go.

2022-05-17 17:38 UTC, merged