Add <10C filter,sss_smos_esa.yaml
NOAA-EMC/godas pull request #356
Opened 2022-07-21 15:58 UTC by ShastriPaturi

## Description
This PR adds the <10C "passivate" filter in sss_smap_jpl.yaml & sss_trak_fnmoc.yaml.
Creates sss_smos_esa.yaml that was missing.

### Issue(s) addressed
Closes #355

2022-07-21 16:42 UTC, mjhossen commented
The soca directory should be under gdas directory. Also, please remove comments, such as
```
  # Passivate obs where ocean fraction is > 90%
  #  - filter: Domain Check
  #    action:
  #      name: passivate
  #    where:
  #    - variable: {name: sea_area_fraction@GeoVaLs}
  #      maxvalue: 0.9
```

2022-07-25 11:51 UTC, guillaumevernieres requested changes

2022-07-25 11:51 UTC, guillaumevernieres commented on soca/obs/sss_smap_jpl.yaml
> +  # Passivate obs where ocean fraction is > 90%
they should be passive by default , un-comment the lines below.

2022-07-25 11:51 UTC, guillaumevernieres commented on soca/obs/sss_smos_esa.yaml
> +  # Passivate obs where ocean fraction is > 90%
Same comment as above. sss is passive by default, at least for now.

2022-07-25 11:51 UTC, guillaumevernieres commented on soca/obs/sss_trak_fnmoc.yaml
> +  # Passivate obs where ocean fraction is > 90%
... Oops ... Looks like I was not paying attention, these should have been passive for sure. We need to be a bit more careful when we put these yaml files together. Ouch.

2022-07-25 12:30 UTC, guillaumevernieres approved these changes

2022-07-25 13:08 UTC, liuxiao37k commented
Do we never have a coastal grid with sea_area_fraction@GeoVaLs < 0.9? Just curious why a threshold of 0.9, not something like 0.999...

2022-07-25 13:37 UTC, guillaumevernieres commented
> Do we never have a coastal grid with sea_area_fraction@GeoVaLs < 0.9? Just curious why a threshold of 0.9, not something like 0.999... I am asking because in L4 adt the passivation mechanism also includes a rejection for coastal obs with sea_area_fraction@GeoVaLs < 0.9, which I understand (i.e. "never trust nearshore obs, even don't use them for validation")
> 
> ```
> # Reject obs where ocean fraction is < 90%
>   - filter: Domain Check
>     action:
>       name: reject
>     where:
>     - variable: {name: sea_area_fraction@GeoVaLs}
>       minvalue: 0.9
>   # Passivate obs where ocean fraction is > 90%
>   - filter: Domain Check
>     action:
>       name: passivate
>     where:
>     - variable: {name: sea_area_fraction@GeoVaLs}
>       maxvalue: 0.9
> ```

@liuxiao37k , these filters work but definitely confuse me, even though I probably was the one originally adding that stuff to the `yaml`. 
The mask is 0 or 1, nothing in between. Happy to revisit the filters with something that makes more sense, but probably not in this PR.

2022-07-25 13:47 UTC, liuxiao37k approved these changes

2022-07-25 13:50 UTC, liuxiao37k commented
> @liuxiao37k , these filters work but definitely confuse me, even though I probably was the one originally adding that stuff to the `yaml`. The mask is 0 or 1, nothing in between. Happy to revisit the filters with something that makes more sense, but probably not in this PR.

@guillaumevernieres Thanks! Sounds good. I have been checking and I can see these filters work just fine, but curious if there is any history behind the number 0.9.

2022-07-25 14:27 UTC, guillaumevernieres commented
> > @liuxiao37k , these filters work but definitely confuse me, even though I probably was the one originally adding that stuff to the `yaml`. The mask is 0 or 1, nothing in between. Happy to revisit the filters with something that makes more sense, but probably not in this PR.
> 
> @guillaumevernieres Thanks! Sounds good. I have been checking and I can see these filters work just fine, but curious if there is any history behind the number 0.9.

yes, it's an interesting story. @guillaumevernieres was having a senior moment and forgot that the mask was 0 OR 1 ... and got confused in the other instance.

2022-07-25 14:28 UTC, merged