Temporary low res forecast model
NOAA-EMC/godas pull request #90
Opened 2019-10-20 01:47 UTC by guillaumevernieres

This PR adds the oops driven mom6 for the forecast step. 
* Default resolution is now 360x210x75, 1440x1080x75 can be used by editing "default/places.yaml"
* "Checkpoint" and "forecast" are in the 3dvar jjob scripts. Both application will fail for the 1/4 deg model, I'm assuming this is OK since the intent is to run the 1/4 deg when the emc model is part of this work flow.

2019-10-20 14:51 UTC, flampouris requested changes
Add the forecast.yaml to the soca-config.

2019-10-20 14:51 UTC, flampouris commented on jobs/JJOB_DA_PREP
> +# Copy SOCA static files into RUNDIR
RUNCDATE instead of RUNDIR, for consistency

2019-10-20 14:51 UTC, flampouris commented on jobs/JJOB_DA_PREP
> +# Copy SOCA config files into RUNDIR
RUNCDATE instead of RUNDIR, for consistency

2019-10-20 14:51 UTC, flampouris commented on workflow/cases/3dvar.yaml
> +    EDATE: 2011-10-30t12:00:00
Let's keep it for 2days long.

2019-10-20 14:59 UTC, guillaumevernieres commented
> Add the forecast.yaml to the soca-config.

It should be in the soca-config, maybe pull again?

2019-10-20 15:01 UTC, flampouris commented
I don't see it: https://github.com/JCSDA/soca-config/tree/develop/emc

2019-10-20 15:02 UTC, guillaumevernieres commented
> I don't see it: https://github.com/JCSDA/soca-config/tree/develop/emc

readme points to feature/emc-3dvar, not in develop yet.

2019-10-20 15:02 UTC, guillaumevernieres commented on workflow/cases/3dvar.yaml
> +    EDATE: 2011-10-30t12:00:00
sorry, got carried away!

2019-10-20 15:10 UTC, flampouris commented
😬 my bad

2019-10-20 15:11 UTC, guillaumevernieres commented
Just pushed the changes

2019-10-20 16:21 UTC, flampouris approved these changes
Tested for two days and works. But adding the model is a significant change, so let's wait till tomorrow for merging, to have the second review from @JessicaMeixner-NOAA.

Also, we have to communicate the change to all the users.

2019-10-21 12:51 UTC, JessicaMeixner-NOAA approved these changes

2019-10-21 13:05 UTC, merged